### ISSUE TITLE
Clipboard not working on first click in windows

### ISSUE THREAD

**Issue by austriker27** [ryangjchandler/alpine-clipboard#7] opened 2021-02-15 23:15 UTC
On windows Im seeing an odd bug that I think is isolated to this package. 

Browsers: Firefox and Edge (I believe they found were using Edge Chromium)

Basically on first click, nothing is copied to the clipboard, but on second click it works. 

`@click="$clipboard(embedCode)"`

Note: This was in version 0.2.0. I will update to 1.0 and re-test. 
Update: I updated to 1.0 and still get the bug.

Thanks!

**Comment by ryangjchandler** [comment] 2021-02-19 22:32
@austriker27 did you try adding `.prevent` to the handler?

**Comment by austriker27** [comment] 2021-02-19 22:36
> @austriker27 did you try adding `.prevent` to the handler?

Interesting idea, I didn't think stopping the event would be different on windows but I'll give it a try!

**Comment by ryangjchandler** [comment] 2021-02-19 22:43
> > @austriker27 did you try adding `.prevent` to the handler?
> 
> Nope. Interesting idea, I didn't think stopping the event would be different on windows but I'll give it a try!

I haven't tested yet, but it's just an idea.

**Comment by austriker27** [comment] 2021-03-12 17:44
I can confirm using `@click.prevent` does not fix the windows copy bug.

**Comment by ryangjchandler** [comment] 2021-03-25 16:05
@austriker27 Going to close this since I can't reproduce the problem. Feel free to re-open if you are able to reproduce in a CodePen or similar.

**Closed by ryangjchandler** 2021-03-25 16:05 UTC
Labels: cant reproduce
